export const PHASES = {
    LOBBY: 'LOBBY',
    ROLE_REVEAL: 'ROLE_REVEAL',
    NIGHT_INTRO: 'NIGHT_INTRO',
    NIGHT_DOPPELGANGER: 'NIGHT_DOPPELGANGER',
    NIGHT_CUPID: 'NIGHT_CUPID',
    NIGHT_WEREWOLF: 'NIGHT_WEREWOLF',
    NIGHT_MINION: 'NIGHT_MINION',
    NIGHT_SORCERER: 'NIGHT_SORCERER',
    NIGHT_DOCTOR: 'NIGHT_DOCTOR',
    NIGHT_SEER: 'NIGHT_SEER',
    NIGHT_MASON: 'NIGHT_MASON',
    NIGHT_VIGILANTE: 'NIGHT_VIGILANTE',
    HUNTER_ACTION: 'HUNTER_ACTION',
    DAY_REVEAL: 'DAY_REVEAL',
    DAY_VOTE: 'DAY_VOTE',
    GAME_OVER: 'GAME_OVER'
};
