export const PHASES = {
    LOBBY: 'LOBBY',
    ROLE_REVEAL: 'ROLE_REVEAL',
    NIGHT_INTRO: 'NIGHT_INTRO',
    NIGHT_DOPPELGANGER: 'NIGHT_DOPPELGANGER',
    NIGHT_CUPID: 'NIGHT_CUPID',
    NIGHT_WEREWOLF: 'NIGHT_WEREWOLF',
    NIGHT_MINION: 'NIGHT_MINION',
    NIGHT_SORCERER: 'NIGHT_SORCERER',
    NIGHT_DOCTOR: 'NIGHT_DOCTOR',
    NIGHT_SEER: 'NIGHT_SEER',
    NIGHT_MASON: 'NIGHT_MASON',
    NIGHT_VIGILANTE: 'NIGHT_VIGILANTE',
    HUNTER_ACTION: 'HUNTER_ACTION',
    DAY_REVEAL: 'DAY_REVEAL',
    DAY_VOTING: 'DAY_VOTING',
    GAME_OVER: 'GAME_OVER'
};

export const NIGHT_PHASE_SEQUENCE = [
    PHASES.NIGHT_DOPPELGANGER,
    PHASES.NIGHT_CUPID,
    PHASES.NIGHT_WEREWOLF,
    PHASES.NIGHT_MINION,
    PHASES.NIGHT_SORCERER,
    PHASES.NIGHT_DOCTOR,
    PHASES.NIGHT_SEER,
    PHASES.NIGHT_MASON,
    PHASES.NIGHT_VIGILANTE,
];
